apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-listener-deployment
  labels:
    app: http-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-listener
  template:
    metadata:
      labels:
        app: http-listener
    spec:
      containers:
      - name: http-listener-container
        image: antonbiz/http_listener:2.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: http-listener-service
spec:
  selector:
    app: http-listener
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
